### ISSUE TITLE
lack of Denpendencies

### ISSUE THREAD

**Issue by nanxfu** [YaooXu/Q2T#2]
I cloned the hole repository, and try to reproduce the paper. But there are lack of some dependencies:
``` 
from .dagnn import RGAT, DAGNN
from .vec_gnn import VecGNN
from .ode_gnn import ODEGNN
 ```
in the Models\\\__init___.py file

and 
```
Unresolved reference 'torch_geometric' 
Unresolved reference 'torch_geometric' 
```
in the Models\query2triple.py
how do i obtain these  files?
Thanks for your answer

**Comment by nanxfu** [comment]
I see, 
```
from .dagnn import RGAT, DAGNN
from .vec_gnn import VecGNN
from .ode_gnn import ODEGNN
```
has not been used yet.So they could be deleted.And the torch_geometric could install by pip.


But another problem is the
```
from Models.utils import init_weights
```
the **Models.utils** seems to be not exist, so how do i obtain it?

**Comment by YaooXu** [comment]
Thanks for raising this issue! It seems that I forget to ignore some unrelated codes, Models/base_model.py and models.py are not used in Q2T actually, so you can delete these files and comment line 14 and 169-179 in the main.py. I will update my codes later.

**Comment by YaooXu** [comment]
The codes have been updated, and we recommend you to use the latest codes.
