### ISSUE TITLE
关于论文中的EFOL疑问

### ISSUE THREAD

**Issue by nanxfu** [YaooXu/Q2T#4]
作者你好，首先十分感谢你撰写这篇论文。阅读了您的论文后我对论文中提到的**EFO-1**表达式产生了些许困惑
![image](https://github.com/YaooXu/Q2T/assets/36119106/9a01648a-1ec3-4a21-b068-4375f56a0bbe)
1.为什么要引入这个表达式的概念
纵观全文，一阶逻辑查询的概念在我看来仅仅是对自然查询语言/计算图的一种补充解释。在阅读完[Beta Embeddings for Multi-Hop Logical Reasoning in Knowledge Graphs](https://arxiv.org/abs/2010.11465).这篇文献后依然无法解答心中的疑虑。

既然模型操作输入的是一个处理好的计算图（？）那为何强调了FOL转DNF的重要性呢。该表达式是否是描述了知识图谱问答中的一类查询类型（？）

2.DNF形式下的EFO-1在代码中是否有体现
或许是我论文阅读量过少，无法理解这一概念的重要性。那么在代码中是否存在这一概念对源数据进行约束处理呢？
感谢您的耐心解答喵~=￣ω￣=

**Comment by YaooXu** [comment]
因为这些模型都不能直接支持析取（并集）操作，只能把包含析取操作的查询转化为多个不包含析取操作的子查询，然后对所有的子答案的预测结果取max，代码中的数据预处理包含这一部分内容。

**Comment by nanxfu** [comment]
原来如此，这么一说我就明白了。感谢解答喵~
