### ISSUE TITLE
否定查询的处理

### ISSUE THREAD

**Issue by nanxfu** [YaooXu/Q2T#6]
在 **4.2.1** 小节您提到了为了区分肯定查询与否定查询，使 S1 矩阵中的第i个否定关系元素的嵌入经过一个线性转换层做变换。

我的理解是S1矩阵中的嵌入都是经过预训练的KGE生成的，已经不会变化了。那变换这个否定关系嵌入的A矩阵是如何确定的呢？如果这个A矩阵是可训练的，那它在哪一步得到了学习？
![image](https://github.com/YaooXu/Q2T/assets/36119106/0f219a08-c5fa-46a2-a0aa-62709a885aef)

感谢解答！！

**Comment by YaooXu** [comment]
该矩阵也是可学习的参数，代码里是这一部分https://github.com/YaooXu/Q2T/blob/893c14d53e375ee9eaec1845203199bb4e6cea90/models/query2triple.py#L329-L333
